# language: en

@SS
@OLCS-21390
Business Need: A TM should no longer be able to access a download link to the TM1 form from VOL, or expect to have a form sent to them via email from VOL.
Feature: Remove reference to TM1 form

Scenario: Update text to remove any reference to the form

Given i have a valid "goods" licence
And i have logged in to self serve
When i add a new transport manager
Then a transport manager has been created banner is displayed

# Source feature: src/test/resources/features/SelfServe/add-tm-banner-check.feature
# Generated by Cucable

