# language: en

@INT
@Admin-Payment-Processing
Feature: Admin payment process

Scenario: Process GB payment by cash and card

Given i have logged in to internal
Given i am on the payment processing page
When when i pay for the fee by "card"
Then the fee should be paid and no longer visible in the fees table

# Source feature: src/test/resources/features/Internal/admin-processing-pay-fee.feature
# Generated by Cucable

