# language: en

@INT
@Admin-Payment-create-fee
Feature: Admin payment process

Scenario: Internal Admin Create Processing Fees

Given i have logged in to internal
Given i am on the payment processing page
When i add a new "NETA Bus Fine" fee
Then the fee should be created

# Source feature: src/test/resources/features/Internal/admin-payment-processing.feature
# Generated by Cucable

