# language: en

@OLCS-21213
@SS-Verify-On
Feature: Operator signs with verify

Scenario: Operator chooses to sign with verify latin and non latin characters

Given i have an application in progress
When i choose to sign with verify with "pavlov"
Then the application should be signed with verify

# Source feature: src/test/resources/features/SelfServe/application-sign-with-verify.feature
# Generated by Cucable

