# language: en

@INT
@APPLY-GOODS-LICENCE
Feature: Apply for a goods licence

Scenario: Apply for a standard national licence

Given I have applied for a "goods" "standard_national" licence
When I grant licence
Then the licence should be granted

# Source feature: src/test/resources/features/Internal/apply-goods-licence.feature
# Generated by Cucable

