# language: en

@OLCS-22443
Feature: Surrendering a licence

Scenario: Another user attempts to surrender my licence

Given i have a valid "public" licence
And surrenders has been switched "on"
Given as a selfserve user i apply for a "goods" licence
Then as "selfserve" user I can surrender a licence
And another user is unable to surrender my licence
And another user is unable to update my surrender details

# Source feature: src/test/resources/features/SelfServe/backend-surrender.feature
# Generated by Cucable

