# language: en

@INT
@OLCS-22443
Feature: Surrenders toggle switched off

Scenario: As an internal user I am unable to use any surrender feature

Given surrenders has been switched "off"
When i have a valid "public" licence
Then as "internal" user I cannot surrender a licence
Then as "internal" user I cannot update a surrender
Then as "internal" user I cannot delete a surrender

# Source feature: src/test/resources/features/Internal/backend-surrender-off.feature
# Generated by Cucable

