# language: en

@SS
@BETA-BANNER
Feature: Selfserve beta banner background is blue

Scenario: Check beta banner colour

Given I am on Selfserve homepage
Then banner colour is blue

# Source feature: src/test/resources/features/SelfServe/beta-banner-check.feature
# Generated by Cucable

