# language: en

@INT
@CASE-DETAILS
Feature: Add case details

@CaseNote
Scenario: Add a case note

Given i have a valid "goods" licence
And I create a new case
When I add notes
Then case notes should be created

# Source feature: src/test/resources/features/Internal/case-details.feature
# Generated by Cucable

