# language: en

@INT
@CASE-CREATION
Feature: Create a new case

Scenario: Creating a case with case notes

Given i have a valid "goods" licence
When I create a new case
Then I should be able to view the case details

# Source feature: src/test/resources/features/Internal/case-creation.feature
# Generated by Cucable

