# language: en

@SS-TM-Verify
@SS
@OLCS-21298
Feature: TM/operator checks optional wording has been removed for TM details page

Scenario: Check section contains

Given I have a new application
And i navigate to the transport managers details page
When I click on the "Add other employment" button
Then I should be taken to the "add-employment" page
And page title "Add employment" should be displayed on page

# Source feature: src/test/resources/features/SelfServe/check-tm-details.feature
# Generated by Cucable

