# language: en

@SS-TM-Verify
@SS
@OLCS-21298
Feature: TM/operator checks optional wording has been removed for TM details page

Scenario: Radio button not clicked

Given I have a new application
And i navigate to the transport managers details page
Then the optional wording should not be displayed on the page
|Other Licences|
|Other Employments|
|previous Convictions|
|previous Licences|
And the section buttons should not be displayed
|Add other licences|
|Add other employment|
|Add convictions and penalties|
|Add licences|

# Source feature: src/test/resources/features/SelfServe/check-tm-details.feature
# Generated by Cucable

