# language: en

@SS-TM-Verify
@SS
@OLCS-21298
Feature: TM/operator checks optional wording has been removed for TM details page

Scenario: validation checks when no radio button has been selected

Given I have a new application
And i navigate to the transport managers details page
When the users attempts to save without entering any data
Then a validation message should be displayed

# Source feature: src/test/resources/features/SelfServe/check-tm-details.feature
# Generated by Cucable

