# language: en

@SS
@SS-ADD-DIRECTOR
Feature: Add a director variation

Scenario: Director with convictions check for snapshot in internal

Given i have a valid "public" licence
And i have logged in to self serve
When a new director has been added
Then a snapshot should be created in internal

# Source feature: src/test/resources/features/SelfServe/director-variation.feature
# Generated by Cucable

