# language: en

@SS
@SS-ADD-DIRECTOR
Feature: Add a director variation

Scenario: Add multiple directors

Given i have a valid "public" licence
And i have logged in to self serve
When i add a director
And i add a new director
Then i should have multiple directors on my application

# Source feature: src/test/resources/features/SelfServe/director-variation.feature
# Generated by Cucable

