# language: en

@SS
@SS-ADD-DIRECTOR
Feature: Add a director variation

Scenario: Task should be created in internal when last TM is removed

Given i have a valid "public" licence
And i have logged in to self serve
When i remove a the last director
Then a task is created in internal

# Source feature: src/test/resources/features/SelfServe/director-variation.feature
# Generated by Cucable

