# language: en

@SS
@SS-ADD-DIRECTOR
Feature: Add a director variation

Scenario: Director without any convictions

Given i have a valid "public" licence
And i have logged in to self serve
When i add a new person
And i enter "No" to financial details question
And i enter "No" previous convictions details question
Then a new director should be added to my licence
And a non urgent task is created in internal

# Source feature: src/test/resources/features/SelfServe/director-variation.feature
# Generated by Cucable

