# language: en

@SS
@SS-ADD-DIRECTOR
Feature: Add a director variation

Scenario: No task should be created for removing person

Given i have a valid "public" licence
And i have logged in to self serve
When i add a director
And i remove a director
Then a task should not be created in internal

# Source feature: src/test/resources/features/SelfServe/director-variation.feature
# Generated by Cucable

