# language: en

@SS
@ESBR
Feature: ESBR for English, Welsh and Scottish Areas

Scenario: Short notice ESBR in self-serve

Given I have a psv application with traffic area "G" and enforcement area "EA-E" which has been granted
When I upload an esbr file with "55" days notice
Then A short notice flag should be displayed in selfserve

# Source feature: src/test/resources/features/SelfServe/esbr.feature
# Generated by Cucable

