# language: en

@SS
@External-Search-Filter
Feature: Using filters on External Search

Scenario: Check lorry and bus operator Organisation Type filter

Given i have a valid "goods" licence
And i have searched for a licence
Then the Organisation Type filter should be displayed

# Source feature: src/test/resources/features/SelfServe/external-search-filter.feature
# Generated by Cucable

