# language: en

@INT
@Generate-Letter
Feature: Generate letter pop up should contain letter details

Scenario: Check generate letter pop up

Given i have a valid "goods" licence
And i have logged in to internal
And i search for my licence
When I generate a letter
Then The pop up should contain letter details

# Source feature: src/test/resources/features/Internal/generate-letter.feature
# Generated by Cucable

