# language: en

@SS
@SS-GOODS-VAR-OC-DECREASE-VEHICLE
@OLCS-20946
Feature: Goods Variation decrease vehicle count for an OC

Scenario: Decreasing the vehicle count to an invalid character for authorised vehicles

Given i have a valid "goods" licence
When A selfserve user decreases the vehicle authority by invalid charecters
Then An error should appear

# Source feature: src/test/resources/features/SelfServe/goods-variation-decrease-vehicle-count-for-oc.feature
# Generated by Cucable

