# language: en

@OLCS-21939
Feature: Digital Surrender - Goods Surrender licence

Scenario: Goods review details page

Given i have a valid "goods" licence
And i choose to surrender my licence
When i am on the review contact details page
Then the correct licence details should be displayed
And the correct correspondence details should be displayed
And the correct contact details should be displayed

# Source feature: src/test/resources/features/SelfServe/goods-surrenders.feature
# Generated by Cucable

