# language: en

@SS
@SS-GOODS-VAR-OC-DECREASE-VEHICLE
@OLCS-20946
Feature: Goods Variation decrease vehicle count for an OC

Scenario: Create a variation and decrease vehicle count

Given i have a valid "goods" licence
When A selfserve user decreases the vehicle authority count
Then a status of update required should be shown next to Review and declarations

# Source feature: src/test/resources/features/SelfServe/goods-variation-decrease-vehicle-count-for-oc.feature
# Generated by Cucable

