# language: en

@OLCS-21939
Feature: Digital Surrender - Goods Surrender licence

Scenario: Update correspondence details

Given i have a valid "goods" licence
And i choose to surrender my licence
When i am on the review contact details page
And i update my correspondence address
Then the new correspondence details should be displayed on the review page

# Source feature: src/test/resources/features/SelfServe/goods-surrenders.feature
# Generated by Cucable

