# language: en

@OLCS-17639
@INT
@INTERIM-NO-DATES
Feature: Change Date Validation On Interim Applications

Scenario: Date required when granting an interim application

Given i have a valid "goods" licence
And i have logged in to internal
And i search for my licence
When I create an interim application with a start and no end date
Then I should error when i attempt to grant the application

# Source feature: src/test/resources/features/Internal/interim-licence-no-dates.feature
# Generated by Cucable

