# language: en

@INT
@INT-LAST-TM-TRIGGER
@OLCS-19479
Feature: Set and check criteria for triggering automatic letter

Scenario: Generate letter for curtail licence

Given i have a valid "public" licence
Given the licence status is "curtail"
When the transport manager has been removed by an internal user
And the user confirms they want to send letter
Then a flag should be set in the DB

# Source feature: src/test/resources/features/Internal/psv-last-tm-letter-trigger.feature
# Generated by Cucable

