# language: en

@OLCS-19478
@INT
@LAST-TM-POP-UP
Feature: Remove last Transport Manager (TM) pop up

Scenario: Error message should be displayed if no option is chosen

Given i have an application with a transport manager
Given the licence has been granted
When the transport manager has been removed by an internal user
And user attempts to remove the last TM without selecting an option
Then an error message should be displayed

# Source feature: src/test/resources/features/Internal/remove-tm-pop-up.feature
# Generated by Cucable

