# language: en

@SS-PASSWORD-RESET
Feature: resetting password with valid/invalid user

Scenario: try reset password for inactive user

Given i have a valid "goods" licence
And i then try reset my password
Then i will receive an error for inactive account

# Source feature: src/test/resources/features/SelfServe/resetting-password.feature
# Generated by Cucable

