# language: en

@SS-PASSWORD-RESET
Feature: resetting password with valid/invalid user

Scenario: reset password for valid user

Given i have a valid "goods" licence
And i reset my password
Then i will receive a message to say my password has changed

# Source feature: src/test/resources/features/SelfServe/resetting-password.feature
# Generated by Cucable

