# language: en

@SS
@GRANT-PSV-APP
Feature: Self Serve Apply for psv licence

Scenario: Pay application and grant fees on selfserve

Given i have a "public" application
When i choose to print and sign
Then the application should be submitted

# Source feature: src/test/resources/features/SelfServe/ss-apply-psv-licence.feature
# Generated by Cucable

