# language: en

@SS
@Surrender-Verify
Feature: Sign with surrender

Scenario: Sign with verify - check that surrender has been created

Given i have a valid "public" licence
And i choose to surrender my licence
And i am on the review contact details page
When i sign with verify
Then the post verify success page is displayed
And the surrender status is "Surrender pending"

# Source feature: src/test/resources/features/SelfServe/surrender-sign-with-verify.feature
# Generated by Cucable

