# language: en

@SS-Verify-On
@OLCS-19792
Feature: TM signs through verify

Scenario: Operator co-signs through Verify

Given verify has been switched "On"
And I am the operator and not the transport manager
And i have a "goods" "GB" partial application
When i add an existing person as a transport manager who is not the operator
And i sign the declaration
Then i choose to sign with verify with "pavlov"
And the operator countersigns digitally
And the 'Review and declarations' post signature page is displayed

# Source feature: src/test/resources/features/SelfServe/tm-verify-on-different-operator.feature
# Generated by Cucable

