# language: en

@SS-Verify-On
@OLCS-19792
Feature: TM signs through verify

Scenario: TM who is not Operator / Applicant signs through Verify

Given verify has been switched "On"
And I am the operator and not the transport manager
And i have a "goods" "GB" partial application
When i add an existing person as a transport manager who is not the operator
And i sign the declaration
And i choose to sign with verify with "pavlov"
Then the 'Awaiting operator review' post signature page is displayed

# Source feature: src/test/resources/features/SelfServe/tm-verify-on-different-operator.feature
# Generated by Cucable

