# language: en

@Verify-Off
Feature: Countersigning declaration page for the operator (Verify switched off)

@OLCS-21374
Scenario: New countersigning declaration page for the operator (Verify switched off)

Given verify has been switched "off"
When I have a "goods" "GB" partial application
And i add a transport manager
And the transport manager is the owner
When i submit the application
Then the print and sign page is displayed
And the application status is "Not yet received"

# Source feature: src/test/resources/features/SelfServe/tm-verify-off.feature
# Generated by Cucable

