# language: en

@SS-Verify-On
@OLCS-20343
Feature: Countersigning declaration page for the operator (Verify switched on)

Scenario: Check declaration text for NI

Given verify has been switched "On"
When i have a "goods" "NI" partial application
And i add an operator as a transport manager
Then the correct information is displayed on the declaration page

# Source feature: src/test/resources/features/SelfServe/tm-verify-check-declarations-text.feature
# Generated by Cucable

