# language: en

@SS-Verify-On
@OLCS-19792
Feature: TM signs through verify

Scenario: TM who is Operator signs through Verify

Given verify has been switched "On"
And I am the operator and not the transport manager
And i have a "goods" "GB" partial application
When i add an operator as a transport manager
And i sign the declaration
And i choose to sign with verify with "pavlov"
Then the 'Review and declarations' post signature page is displayed

# Source feature: src/test/resources/features/SelfServe/tm-verify-on-different-operator.feature
# Generated by Cucable

