name: Upload Allure Report

on:
  workflow_call:
    inputs:
      build_id:
        description: 'Build ID for the Allure report'
        required: true
        type: string

permissions:
  contents: write
 

jobs:
  upload-allure-report:
    name: Upload Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Download Allure Report
        uses: actions/download-artifact@main
        with:
          name: allure-results
          
      - name: Upload Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/allure-maven-plugin